### ISSUE TITLE
Not working with CIDER 0.17.0 and nREPL 0.2.13

### ISSUE THREAD

**Issue by FerdiKuehne** [pkpkpk/fress#1]
Hello! When i loading fress lib. I getting following error

`/home/ferdi/customer/kommunismus/new-konserve/konserve/.cljs_node_repl/fress/util.js:73
fress.util.TextEncoder = (new TextEncoder("utf8"));
                              ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/ferdi/customer/kommunismus/new-konserve/konserve/.cljs_node_repl/fress/util.js:73:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at global.CLOSURE_IMPORT_SCRIPT (repl:76:9)
    at Object.goog.require (repl:21:8) (node:3318) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.`

i have following node version: `v10.7.0`

**Comment by pkpkpk** [comment]
Thanks for the report, I am looking into this.

Are you by any chance consuming this under :simple opts? Theres a runtime check that appears to be compiled away and it shouldn't be

**Comment by FerdiKuehne** [comment]
yeah, that could be possible i check this. By the way i downgraded my node version to `v9.11.2` and now the DeprecationWarning is gone. 

Best regards ferdi

**Comment by FerdiKuehne** [comment]
Well done! Its working with your newest version `0.2.0 snapshot.`

**Comment by pkpkpk** [comment]
Glad its working but not sure I changed anything that would change what failed. If it pops up again make sure you are on latest cljs and we can reopen this
